language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

sudo: required

services:
  - docker

script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - ansible-playbook -vvv -i ~/repo/localhosts build_cgminer_docker_file.yml
