language: python
python:
- '2.7'
before_install:
- mkdir -p ~\/.ssh/
- chmod 700  ~\/.ssh
- openssl aes-256-cbc -K $encrypted_52ba5e8351e3_key -iv $encrypted_52ba5e8351e3_iv
  -in shapeshift.enc -out shapeshift -d
- ls -lrt *
- ssh-add  ./shapeshift 
- eval "$(ssh-agent -s)"
- chmod 600 shapeshift
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add  ./shapeshift
- ssh -i  ./shapeshift ubuntu@$SERVER_IP_ADDRESS pwd

install:
- pip install -r requirements.txt
sudo: required
services:
- docker
script:
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
- ansible-playbook -i ~/repo/localhosts build_cgminer_docker_file.yml
