language: python
python:
- '2.7'
before_install:
- mkdir -p ~\/.ssh/
- chmod 700  ~\/.ssh
- openssl aes-256-cbc -K $encrypted_52ba5e8351e3_key -iv $encrypted_52ba5e8351e3_iv
  -in cgminer.enc -out  ~\/.ssh/cgminer -d
- chmod 600 ~\/.ssh/cgminer
- eval "$(ssh-agent -s)"
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add  ~\/.ssh/cgminer

install:
- pip install -r requirements.txt
sudo: required
services:
- docker
script:
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
- ansible-playbook -i ~/localhosts build_cgminer_docker_file.yml
deploy:
  skip_cleanup: true
  provider: script
  script:
  - ansible-playbook -i ~/localhosts create_host_file.yml --extra-vars "HOST_IP=$SERVER_IP_ADDRESS SSH_KEY_NAME=cgminer"
  - cat ~/hosts
  - ansible-playbook -i ~/hosts deploy_docker.yml --extra-vars "POOL_URL=$POOL_URL MINER_USER=$MINER_USER  MINER_PASSWD=$MINER_PASSWD"

