---
- hosts: shapeshift
  become: yes
  become_user: root
- name: nginx container
  docker_container:
    image: ohallord/cgminer
    state: started
    restart_policy: always
    restart_policy_retry: 3
    env:
       POOL_URL: "{{ pool_url }}"
       MINER_USER: "{{ miner_user }}"
       MINER_PASSWD: "{{ miner_passwd }}"
    tags:
      - cgminer

