---
- hosts: shapeshift
  tasks:
  - name: deploy and run the docker container
    docker_container:
      name: cgminer
      image: ohallord/cgminer
      state: started
      restart_policy: always
      env:
         POOL_URL: "{{ POOL_URL }}"
         MINER_USER: "{{ MINER_USER }}"
         MINER_PASSWD: "{{ MINER_PASSWD }}"

