version: 2
jobs:
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
  build:
    docker:
      #- image: circleci/python:3.6.1
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run: 
          name: Log into Docker
          command:  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: install dependencies
          command: |
            #python3 -m venv venv
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            ansible-playbook build_cgminer_docker_file.yml
      - save_cache: # special step to save dependency cache
          key: v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: create host file
          command:
             . venv/bin/activate
             ansible-playbook create_host_file.yml --extra-vars "HOST_IP=$EC2_HOST_IP SSH_KEY_NAME=$SSH_KEY_NAME "
  deploy:
    machine:
      enabled: true
    docker:
       #- image: circleci/python:3.6.1
       - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
             - "$SSH_FINGERPRINT"
#87:5a:c7:c8:0e:14:01:c6:cf:9c:c5:02:e4:8b:77:88
      - run:
          name: Check to see what the ssh file name is
          command: |
            echo "The Finger Print is $SSH_FINGERPRINT"
            ls -l ~/.ssh/*
      - run:
          name: install and run the docker file on the host
          command:
             python -m virtualenv venv
             . venv/bin/activate
             pip install -r requirements.txt
             echo "Host Variables are "POOL_URL=$POOL_URL MINER_USER=$MINER_USER  MINER_PASSWD=$MINER_PASSWD"
             ansible-playbook -i hosts deploy_docker.yml --extra-vars "POOL_URL=$POOL_URL MINER_USER=$MINER_USER  MINER_PASSWD=$MINER_PASSWD"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build